apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx:latest
    volumeMounts:
    - name: conf
      mountPath: /data
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes: 
  - name: conf
    configMap:
      name: db-config


--- 

apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
  labels:
    role: web
spec:
  containers:
  - name: nginx-cm
    image: nginx
    volumeMounts:
    - name: conf
      mountPath: "/datatwo"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: conf
    configMap:
      name: db-config
      items:
      - key: nginx-custom-config.conf
        path: default.conf

---
apiVersion: v1
kind: Pod
metadata:
  name: redconfig
  labels:
    name: redconfig
    configmap: "fromred"
spec:
  containers:
  - name: mynginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env: 
      - name: COLOR
        valueFrom:
          configMapKeyRef:
            name: myconfig
            key: color
  restartPolicy: Never        