apiVersion: v1
kind: PersistentVolume
metadata:
  name: demovolume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demovolumetwo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/datatwo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demopvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: myngnixdemo
  labels:
    name: myngnixdemo
spec:
  containers:
  - name: mynginxone
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name  : "mypvc"
        mountPath: "/directoryinpod"
  volumes:
    - name : "mypvc"
      persistentVolumeClaim: 
        claimName: "demopvc"





