# This is actually an example of mounting a secret. 
# secrets will be mounted into directories and will result 
# in the file names. 
apiVersion: v1
kind: Pod
metadata:
  name: secretpods
  labels:
    name: secretpods
spec:
  containers:
  - name: myapp
    image: busybox
    command: 
      - sleep 
      - "3600"
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /secretstuff
      name: secret
  volumes:
    - name: secret
      secret:
        secretName:  "mysecret"
--- 

# This will set up as the environment variables. 
apiVersion: v1
kind: Pod
metadata:
  name: newsecretpod
  labels:
    name: newsecretpod
spec:
  containers:
  - name: myapp2
    image: busybox 
    command: 
      - sleep 
      - "3600"
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    env: 
    - name : "MYSQL_ROOT_PASSWORD"
      valueFrom: 
        secretKeyRef: 
          name: mysecret
          key: "datta"