apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mynginxdep
  name: mynginxdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginxdep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mynginxdep
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
