apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mynginxdep
  name: mynginxdep
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30011
  selector:
    app: mynginxdep
status:
  loadBalancer: {}
