apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: centos1
    image: centos:7
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    command: 
    - sleep 
    - "3600"
  - name: centos2
    image: centos:7
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    command: 
    - sleep 
    - "3600"
    