apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginxsvc
  name: nginxsvc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxdeploy
status:
  loadBalancer: {}
