apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginxnodeport
  name: nginxnodeport
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 81
    nodePort: 30009
  selector:
    app: nginxdeploy
status:
  loadBalancer: {}
