apiVersion: v1
data:
  nginx-custom-config.conf: "server {\n\tlisten 8888;\n\tserver_name localhost;\n\tlocation
    \ / \t{\n\t\troot /usr/share/nginx/html;\n\t\tindex index.htm index.html\n\t}\n}\n\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: db-config
