apiVersion: v1
kind: Pod
metadata:
  name: redconfig
  labels:
    name: redconfig
    configmap: "fromred"
spec:
  containers:
  - name: mynginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: COLOR
        valueFrom:
          configMapKeyRef:
            name: myconfig
            key: color
  restartPolicy: Never