apiVersion: v1
kind: Pod
metadata:
  name: secretbox2
  labels:
    name: secretbox2
    namespace: default
spec:
  containers:
  - name: secretbox
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - sleep 
      - "3600"
    envFrom:
      - secretRef:
          name: secretstuff