apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpstoragevolume
  labels: 
    name: "Arvind"
    lastname: "Pulijala"
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  