apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx:latest
    volumeMounts:
    - name: conf
      mountPath: /etc/nginx/conf.d
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes: 
  - name: conf
    configMap:
      name: nginx-cm
     
          
--- 

apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
  labels:
    role: web
spec:
  containers:
  - name: nginx-cm
    image: nginx
    volumeMounts:
    - name: conf
      mountPath: /etc/nginx/conf.d
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: conf
    configMap:
      name: nginx-cm
      items:
      - key: nginx-custom-config.conf
        path: default.conf