apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  containers:
  - image: nginx:latest
    name: backend
    volumeMounts:
    - name: db-config-volume
      mountPath: /etc/config/default
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: db-config-volume
    configMap:
      name: db-config