apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-volume
  namespace: myvol
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pv-claim
  namespace: "myvol"
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: myvol
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    volumeMounts:
    - mountPath: /data
      name: local-pv-storage
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: myapp1
    image: nginx
    volumeMounts:
    - mountPath: /data1
      name: local-pv-storage
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes: 
    - name: local-pv-storage
      persistentVolumeClaim: 
        claimName: local-pv-claim
        




